# Generated by Django 4.2.3 on 2024-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_url', models.URLField()),
                ('short_url', models.CharField(max_length=10)),
            ],
        ),
    ]
